// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8_1F_S9GpQTGGjzM7nL0fviYAI8-Ax8Y',
    appId: '1:416179424457:web:4cca915e79334d6755d118',
    messagingSenderId: '416179424457',
    projectId: 'smbw-ee1bd',
    authDomain: 'smbw-ee1bd.firebaseapp.com',
    databaseURL: 'https://smbw-ee1bd-default-rtdb.firebaseio.com',
    storageBucket: 'smbw-ee1bd.firebasestorage.app',
    measurementId: 'G-ED3JVGQRKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0VHXJdRCFml_bcA2WdGCz8dMj15aaMrE',
    appId: '1:416179424457:android:8471b9132ff3f01855d118',
    messagingSenderId: '416179424457',
    projectId: 'smbw-ee1bd',
    databaseURL: 'https://smbw-ee1bd-default-rtdb.firebaseio.com',
    storageBucket: 'smbw-ee1bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH-afeomBMQeiqO6_74ja0DMVtg8j6uFE',
    appId: '1:416179424457:ios:2da32b50bc09f1f755d118',
    messagingSenderId: '416179424457',
    projectId: 'smbw-ee1bd',
    databaseURL: 'https://smbw-ee1bd-default-rtdb.firebaseio.com',
    storageBucket: 'smbw-ee1bd.firebasestorage.app',
    iosClientId: '416179424457-p8n6ntfnh3isod1umq68ett38h6qlfjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.smbw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH-afeomBMQeiqO6_74ja0DMVtg8j6uFE',
    appId: '1:416179424457:ios:2da32b50bc09f1f755d118',
    messagingSenderId: '416179424457',
    projectId: 'smbw-ee1bd',
    databaseURL: 'https://smbw-ee1bd-default-rtdb.firebaseio.com',
    storageBucket: 'smbw-ee1bd.firebasestorage.app',
    iosClientId: '416179424457-p8n6ntfnh3isod1umq68ett38h6qlfjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.smbw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8_1F_S9GpQTGGjzM7nL0fviYAI8-Ax8Y',
    appId: '1:416179424457:web:948ac9568389ce8655d118',
    messagingSenderId: '416179424457',
    projectId: 'smbw-ee1bd',
    authDomain: 'smbw-ee1bd.firebaseapp.com',
    databaseURL: 'https://smbw-ee1bd-default-rtdb.firebaseio.com',
    storageBucket: 'smbw-ee1bd.firebasestorage.app',
    measurementId: 'G-X4TLW1Y4LM',
  );

}